theme: jekyll-theme-slate
title: KEXP Now Playing Browser Extension
description: A browser extension that displays the track, artist and album from the currently playing track on 90.3 KEXP. When the user clicks on the browser extension icon a window appears to display the album artwork (if available) song, artist and album.
